# Site basics
title: dEN5-tech's Project Site
description: Bookmark this to keep an eye on my project updates!

# Core paths
baseurl: ""
url: "https://den5-tech.github.io"

# Essential includes
include:
  - resource
  - resource/RSE.html

# File handling
defaults:
  - scope:
      path: "resource/RSE.html"
    values:
      permalink: /resource/RSE.html

# Basic build settings
markdown: kramdown
encoding: UTF-8
safe: true
